sudo mkdir ~/Pictures/Screenshots
sudo mkdir ~/Projects
chflags hidden ~/Documents
chflags hidden ~/Public
chflags hidden ~/Movies
chflags hidden ~/Music
chmod 000 ~/Documents
chmod 000 ~/Public 
chmod 000 ~/Movies
chmod 000 ~/Music
